[package]
name = "aurora-engine-sdk"
version = "1.0.0"
authors = ["Aurora Labs <hello@aurora.dev>"]
edition = "2021"
description = ""
documentation = ""
readme = true
homepage = "https://github.com/aurora-is-near/aurora-engine"
repository = "https://github.com/aurora-is-near/aurora-engine"
license = "CC0-1.0"
publish = false
autobenches = false

[dependencies]
aurora-engine-types = { path = "../engine-types" }
borsh = "0.8.2"
sha3 = { version = "0.9.1", default-features = false }
sha2 = { version = "0.9.3", default-features = false }

[features]
contract = []
log = []
mainnet = []
testnet = []
