[package]
name = "aurora-engine-tests"
version = "1.0.0"
authors = ["Aurora Labs <hello@aurora.dev>"]
edition = "2021"
description = ""
documentation = ""
readme = true
homepage = "https://github.com/aurora-is-near/aurora-engine"
repository = "https://github.com/aurora-is-near/aurora-engine"
license = "GPL-3.0"
publish = false
autobenches = false

[dependencies]
anyhow = "1.0"
aurora-engine = { path = "../engine", default-features = false, features = ["std", "tracing", "impl-serde"] }
aurora-engine-types = { path = "../engine-types", default-features = false, features = ["std", "impl-serde"] }
aurora-engine-sdk = { path = "../engine-sdk", default-features = false, features = ["std"] }
aurora-engine-precompiles = { path = "../engine-precompiles", default-features = false, features = ["std"] }
aurora-engine-transactions = { path = "../engine-transactions", default-features = false, features = ["std"] }
engine-standalone-storage = { path = "../engine-standalone-storage" }
engine-standalone-tracing = { path = "../engine-standalone-tracing" }
borsh = { version = "0.9.3", default-features = false }
sha3 = { version = "0.10.2", default-features = false }
evm = { git = "https://github.com/aurora-is-near/sputnikvm.git", tag = "v0.36.0-aurora", default-features = false, features = ["std", "tracing"] }
evm-runtime = { git = "https://github.com/aurora-is-near/sputnikvm.git", tag = "v0.36.0-aurora", default-features = false, features = ["std", "tracing"] }
evm-gasometer = { git = "https://github.com/aurora-is-near/sputnikvm.git", tag = "v0.36.0-aurora", default-features = false, features = ["std", "tracing"] }
rlp = { version = "0.5.0", default-features = false }
base64 = "0.13.0"
bstr = "0.2"
byte-slice-cast = { version = "1.0", default-features = false }
ethabi = "17.1" 
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = { version = "0.4.3", default-features = false }
near-sdk = { git = "https://github.com/near/near-sdk-rs.git", tag = "4.0.0" }
near-crypto = { git = "https://github.com/near/nearcore.git",tag = "1.28.1" }
near-vm-errors = { git = "https://github.com/near/nearcore.git", tag = "1.28.1", default-features = false }
near-vm-runner = { git = "https://github.com/near/nearcore.git", tag = "1.28.1", default-features = false, features = ["wasmer2_vm"] }
near-vm-logic = { git = "https://github.com/near/nearcore.git", tag = "1.28.1", default-features = false }
near-primitives-core = { git = "https://github.com/near/nearcore.git", tag = "1.28.1" }
near-primitives = { git = "https://github.com/near/nearcore.git", tag = "1.28.1", default-features = false, features = ["nightly_protocol"] }
near-units = "0.2.0"
libsecp256k1 = { version = "0.7.0", default-features = false }
rand = "0.8.5"
criterion = "0.3.4"
git2 = "0.13"
tempfile = "3.2.0"
tokio = { version = "1.10.0", features = ["full"] }
walrus = "0.19"
aurora-workspace = { git = "https://github.com/aurora-is-near/aurora-workspace.git", features = ["deposit-withdraw"], rev = "cc90b3c53ffe8b988563c31ba02ce281e65ec0ba" }
workspaces = { git = "https://github.com/near/workspaces-rs.git", rev = "5311791a5a1654d1ba45fd318ed967abce25999d" }

[features]
mainnet-test = []
testnet-test = []
error_refund = ["aurora-engine/error_refund", "aurora-engine-precompiles/error_refund"]
