---
on:
  push:
    branches:
      - master
      - develop
  pull_request:

name: Tests
jobs:
  test:
    name: Test suite (mainnet, testnet)
    runs-on: [self-hosted, heavy]
    steps:
      - name: Potential broken submodules fix
        run: |
          git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Restore cache
        run: |
          cache-util restore cargo_git cargo_registry sccache yarn_cache
          cache-util restore aurora-engine-target@generic@${{ hashFiles('**/Cargo.lock') }}:target
      - name: Run Mainnet Tests
        run: cargo make --profile mainnet test
      - name: Run Testnet Tests
        run: cargo make --profile testnet test        
      - name: List mainnet WASM directory and root directory
        run: ls -la target/wasm32-unknown-unknown/release && ls -la
      - name: List testnet WASM directory and root directory
        run: ls -la target/wasm32-unknown-unknown/release && ls -la
      - name: Save cache
        run: |
          cache-util save cargo_git cargo_registry sccache yarn_cache
          cache-util msave aurora-engine-target@generic@${{ hashFiles('**/Cargo.lock') }}:target
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

